### ISSUE TITLE
change Create Mass Withdrawal Response format

### ISSUE THREAD

**Issue by nyancodeid** [OrahKokos/coinpayments#10]
Plase make array object format to make easy to use for response result.

Example response from server now
```javascript
{ 
  wd1: { 
    error: 'ok',
    id: 'CWBF3UECUQFCCNFIRUS73G5VON',
    status: 1,
    amount: '1.00000000' 
  },
  wd2: {
    error: 'That amount is larger than your balance!' 
  }
}
```

make it into

```javascript
[
  {
    error: "ok",
    id: "CWBF3UECUQFCCNFIRUS73G5VON",
    status: 1,
    amount: 1.00000000
  },
  {
    error: "That amount is larger than your balance!"
  }
]
```

Thanks

**Comment by MarkoParoski** [comment]
Hello @nyancodeid,
Thank you for the feedback.
I understand that the formatting is bad in this request, however this is something intended: Docs: https://www.coinpayments.net/apidoc-create-withdrawal

Since API sometimes don't have well documented responses, it is for the best to keep what the developers from coinpayments intended. Also, changing this will affect developers/applications which are already running and would require a tick to version 2.0 ( breaking changes ). Until there is sufficient/relevant features I am not ready to make this transition to 2.0. 

I'd suggest that you should format this on the application level after receiving the ugly (but intended) response.

**Comment by OrahKokos** [comment]
Hello @nyancodeid,
Thank you for the feedback.
I understand that the formatting is bad in this request, however this is something intended: Docs: https://www.coinpayments.net/apidoc-create-withdrawal

Since API sometimes don't have well documented responses, it is for the best to keep what the developers from coinpayments intended. Also, changing this will affect developers/applications which are already running and would require a tick to version 2.0 ( breaking changes ). Until there is sufficient/relevant features I am not ready to make this transition to 2.0.

I'd suggest that you should format this on the application level after receiving the ugly (but intended) response.
