### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by Benjythebee** [OrahKokos/coinpayments#82]
Heya, what's the status on the maintenance of this repo?

I don't see a lot of activity since 2022

**Comment by OrahKokos** [comment]
Greetings @Benjythebee,

I'm still around, if something needs fixing.
Currently there is no need to update anything since Coinpayments API contract did not change, so no need to update anything. 
I would like to publish the 3.0.0 version, however i'm having some issues passing their KYC due to some life-related situation.

If there is anything else, please let me know.
Cheers
